version: "3.9"

services:
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: timescale-gravity-db
    environment:
      POSTGRES_DB: trading
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_setup.sql:/docker-entrypoint-initdb.d/001-db-setup.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d trading"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: timescale-gravity-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PGHOST: db
      PGPORT: "5432"
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: trading
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  db_data:
